// Builds the submission packet entirely in the browser with jsPDF. Any file
// (image or PDF, single or multi-page) is flattened to plain-pixel pages first.
// The packet is split into one or more PDFs of no more than maxPages pages each,
// because ClassWallet rejects PDFs over its page limit (see lib/classwallet.json).
import { checkClaim, draftReasoning, PATHWAYS } from "@/lib/rules";
import { fileToPages } from "@/lib/rasterize";
import cw from "@/lib/classwallet.json";

const fmtMoney = (n) => (n || n === 0) ? `$${Number(n).toFixed(2)}` : "—";
const NAVY = [22, 50, 78], MUTED = [113, 118, 127];

function partFooter(doc, part, total, vendor) {
  const W = doc.internal.pageSize.getWidth(), H = doc.internal.pageSize.getHeight();
  doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(...MUTED);
  const left = total > 1 ? `ClearClaim · ${vendor || "packet"} · file ${part} of ${total}` : "Generated by ClearClaim. Attach this packet with your submission.";
  doc.text(left, 48, H - 22);
}

// Draws the cover on the current page. Kept to a single page.
function drawCover(doc, claim, kid, images) {
  const W = doc.internal.pageSize.getWidth(), H = doc.internal.pageSize.getHeight(), M = 48;
  let y = M;
  doc.setFillColor(...NAVY); doc.rect(0, 0, W, 70, "F");
  doc.setTextColor(255, 255, 255); doc.setFont("times", "bold"); doc.setFontSize(22);
  doc.text("ClearClaim", M, 44);
  doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.setTextColor(214, 224, 240);
  doc.text("Submission packet", W - M, 44, { align: "right" });
  y = 100;

  doc.setTextColor(...NAVY); doc.setFont("times", "bold"); doc.setFontSize(16);
  doc.text(`${claim.vendor || "Claim"} — ${fmtMoney(claim.amount)}`, M, y); y += 22;

  doc.setFont("helvetica", "normal"); doc.setFontSize(11);
  const pathwayLabel = (PATHWAYS.find(p => p.value === (claim.pathway || "reimbursement")) || {}).label || claim.pathway;
  const kidLine = kid ? `${kid.first_name}${kid.grade ? `, grade ${kid.grade}` : ""}${kid.school_name ? ` · ${kid.school_name}` : ""}` : "—";
  [["Student", kidLine], ["Pathway", pathwayLabel || "—"], ["Date", claim.date || "—"], ["Category", claim.category || "—"], ["Amount", fmtMoney(claim.amount)]]
    .forEach(([k, v]) => { doc.setTextColor(...MUTED); doc.text(k, M, y); doc.setTextColor(30, 34, 42); doc.text(String(v), M + 90, y); y += 18; });
  if (claim.items) {
    y += 4; doc.setTextColor(...MUTED); doc.text("Items", M, y); doc.setTextColor(30, 34, 42);
    const items = doc.splitTextToSize(String(claim.items), W - M - M - 90);
    doc.text(items, M + 90, y); y += items.length * 15 + 4;
  }

  y += 10; doc.setDrawColor(232, 227, 216); doc.line(M, y, W - M, y); y += 20;
  doc.setFont("times", "bold"); doc.setFontSize(13); doc.setTextColor(...NAVY);
  doc.text("Educational-use statement", M, y); y += 18;
  doc.setFont("helvetica", "normal"); doc.setFontSize(11); doc.setTextColor(30, 34, 42);
  const reasoning = claim.reasoning || claim.purpose || draftReasoning(claim, kid);
  const rlines = doc.splitTextToSize(reasoning, W - M - M);
  doc.text(rlines, M, y); y += rlines.length * 15 + 14;

  doc.setFont("times", "bold"); doc.setFontSize(13); doc.setTextColor(...NAVY);
  doc.text("Pre-submission check", M, y); y += 18;
  doc.setFont("helvetica", "normal"); doc.setFontSize(10);
  const checks = checkClaim({ ...claim, receipt_count: images.filter(i => i.kind === "Receipt").length, payment_count: images.filter(i => i.kind === "Bank charge").length });
  for (const c of checks) {
    if (y > H - 60) break; // keep the cover to one page
    const color = c.level === "fail" ? [179, 38, 30] : c.level === "warn" ? [122, 90, 18] : [15, 118, 110];
    const mark = c.level === "fail" ? "✗" : c.level === "warn" ? "!" : "✓";
    doc.setTextColor(...color); doc.text(mark, M, y);
    doc.setTextColor(60, 64, 72);
    const lines = doc.splitTextToSize(c.msg, W - M - M - 16);
    doc.text(lines, M + 16, y); y += lines.length * 13 + 3;
  }
}

function drawSupportingPage(doc, pg) {
  const W = doc.internal.pageSize.getWidth(), H = doc.internal.pageSize.getHeight(), M = 48;
  doc.setFillColor(...NAVY); doc.rect(0, 0, W, 34, "F");
  doc.setTextColor(255, 255, 255); doc.setFont("helvetica", "bold"); doc.setFontSize(11);
  doc.text(pg.label, M, 22);
  if (pg.error) { doc.setTextColor(179, 38, 30); doc.setFontSize(11); doc.text("Attach this file separately.", M, 70); return; }
  const availW = W - M * 2, availH = H - 34 - M * 1.2;
  let dw = availW, dh = availH;
  if (pg.w && pg.h) { const s = Math.min(availW / pg.w, availH / pg.h); dw = pg.w * s; dh = pg.h * s; }
  try { doc.addImage(pg.dataUrl, "JPEG", (W - dw) / 2, 50, dw, dh); }
  catch { doc.setTextColor(179, 38, 30); doc.setFontSize(11); doc.text("Could not embed this page.", M, 70); }
}

// Flatten every supporting doc to page images.
export async function supportingPages(images) {
  const out = [];
  for (const im of images) {
    let pages;
    try { pages = await fileToPages(im.blob); }
    catch { out.push({ error: true, label: `Could not read ${im.kind}${im.name ? ` (${im.name})` : ""}` }); continue; }
    pages.forEach((pg, idx) => out.push({ ...pg, label: im.kind + (im.name ? ` — ${im.name}` : "") + (pages.length > 1 ? ` (page ${idx + 1} of ${pages.length})` : "") }));
  }
  return out;
}

// Returns an array of jsPDF docs, each <= maxPages pages. File 1 holds the cover
// plus supporting pages; later files hold the rest.
export async function buildPacketPdfs(claim, kid, images, maxPages) {
  const { jsPDF } = await import("jspdf");
  const limit = Math.max(1, maxPages || cw.maxPagesPerFile || 5);
  const support = await supportingPages(images);

  const chunks = [{ cover: true, pages: support.slice(0, limit - 1) }];
  let rest = support.slice(limit - 1);
  while (rest.length) { chunks.push({ cover: false, pages: rest.slice(0, limit) }); rest = rest.slice(limit); }

  const total = chunks.length;
  return chunks.map((ch, ci) => {
    const doc = new jsPDF({ unit: "pt", format: "a4" });
    let used = false;
    if (ch.cover) { drawCover(doc, claim, kid, images); used = true; }
    ch.pages.forEach(pg => { if (used) doc.addPage(); else used = true; drawSupportingPage(doc, pg); });
    // footer on every page
    const pageCount = doc.internal.getNumberOfPages();
    for (let p = 1; p <= pageCount; p++) { doc.setPage(p); partFooter(doc, ci + 1, total, claim.vendor); }
    return doc;
  });
}

// Back-compat single-doc builder (first file only). Prefer buildPacketPdfs.
export async function buildPacketPdf(claim, kid, images) {
  const docs = await buildPacketPdfs(claim, kid, images);
  return docs[0];
}
