// Builds the one-file submission packet (cover page + each supporting image)
// entirely in the browser with jsPDF. Shared by the claim builder and the
// claim view page.
import { checkClaim, draftReasoning, PATHWAYS } from "@/lib/rules";

function toDataURL(blob) {
  return new Promise((resolve, reject) => {
    const r = new FileReader();
    r.onload = () => resolve(r.result);
    r.onerror = reject;
    r.readAsDataURL(blob);
  });
}
function imgSize(dataUrl) {
  return new Promise((resolve) => {
    const i = new Image();
    i.onload = () => resolve({ w: i.width, h: i.height });
    i.onerror = () => resolve({ w: 0, h: 0 });
    i.src = dataUrl;
  });
}
const fmtMoney = (n) => (n || n === 0) ? `$${Number(n).toFixed(2)}` : "—";

// claim: {vendor, pathway, amount, date, category, items, purpose, reasoning}
// kid:   {first_name, grade, setting, school_name}
// images: [{kind, blob, name}]
export async function buildPacketPdf(claim, kid, images) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 48;
  let y = M;

  const navy = [22, 50, 78];
  const gold = [198, 138, 28];
  const muted = [113, 118, 127];

  // Header band
  doc.setFillColor(...navy);
  doc.rect(0, 0, W, 70, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("times", "bold");
  doc.setFontSize(22);
  doc.text("ClearClaim", M, 44);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(214, 224, 240);
  doc.text("Submission packet", W - M, 44, { align: "right" });
  y = 100;

  // Title
  doc.setTextColor(...navy);
  doc.setFont("times", "bold");
  doc.setFontSize(16);
  const pathwayLabel = (PATHWAYS.find(p => p.value === (claim.pathway || "reimbursement")) || {}).label || claim.pathway;
  doc.text(`${claim.vendor || "Claim"} — ${fmtMoney(claim.amount)}`, M, y);
  y += 22;

  // Summary rows
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  const kidLine = kid
    ? `${kid.first_name}${kid.grade ? `, grade ${kid.grade}` : ""}${kid.school_name ? ` · ${kid.school_name}` : ""}`
    : "—";
  const rows = [
    ["Student", kidLine],
    ["Pathway", pathwayLabel || "—"],
    ["Date", claim.date || "—"],
    ["Category", claim.category || "—"],
    ["Amount", fmtMoney(claim.amount)],
  ];
  rows.forEach(([k, v]) => {
    doc.setTextColor(...muted); doc.text(k, M, y);
    doc.setTextColor(30, 34, 42); doc.text(String(v), M + 90, y);
    y += 18;
  });
  if (claim.items) {
    y += 4;
    doc.setTextColor(...muted); doc.text("Items", M, y);
    doc.setTextColor(30, 34, 42);
    const items = doc.splitTextToSize(String(claim.items), W - M - M - 90);
    doc.text(items, M + 90, y); y += items.length * 15 + 4;
  }

  // Reasoning
  y += 10;
  doc.setDrawColor(232, 227, 216); doc.line(M, y, W - M, y); y += 20;
  doc.setFont("times", "bold"); doc.setFontSize(13); doc.setTextColor(...navy);
  doc.text("Educational-use statement", M, y); y += 18;
  doc.setFont("helvetica", "normal"); doc.setFontSize(11); doc.setTextColor(30, 34, 42);
  const reasoning = claim.reasoning || claim.purpose || draftReasoning(claim, kid);
  const rlines = doc.splitTextToSize(reasoning, W - M - M);
  doc.text(rlines, M, y); y += rlines.length * 15 + 14;

  // Rules check
  doc.setFont("times", "bold"); doc.setFontSize(13); doc.setTextColor(...navy);
  doc.text("Pre-submission check", M, y); y += 18;
  doc.setFont("helvetica", "normal"); doc.setFontSize(10);
  const checks = checkClaim({
    ...claim,
    receipt_count: images.filter(i => i.kind === "Receipt").length,
    payment_count: images.filter(i => i.kind === "Bank charge").length,
  });
  checks.forEach(c => {
    const color = c.level === "fail" ? [179, 38, 30] : c.level === "warn" ? [122, 90, 18] : [15, 118, 110];
    const mark = c.level === "fail" ? "✗" : c.level === "warn" ? "!" : "✓";
    doc.setTextColor(...color); doc.text(mark, M, y);
    doc.setTextColor(60, 64, 72);
    const lines = doc.splitTextToSize(c.msg, W - M - M - 16);
    doc.text(lines, M + 16, y); y += lines.length * 13 + 3;
    if (y > H - M) { doc.addPage(); y = M; }
  });

  doc.setTextColor(...muted); doc.setFontSize(9);
  doc.text("Generated by ClearClaim. Attach this packet with your submission.", M, H - 30);

  // One page per supporting image
  for (const im of images) {
    const dataUrl = await toDataURL(im.blob);
    const { w, h } = await imgSize(dataUrl);
    doc.addPage();
    doc.setFillColor(...navy); doc.rect(0, 0, W, 34, "F");
    doc.setTextColor(255, 255, 255); doc.setFont("helvetica", "bold"); doc.setFontSize(11);
    doc.text(im.kind + (im.name ? ` — ${im.name}` : ""), M, 22);
    const availW = W - M * 2;
    const availH = H - 34 - M * 1.2;
    let dw = availW, dh = availH;
    if (w && h) {
      const scale = Math.min(availW / w, availH / h);
      dw = w * scale; dh = h * scale;
    }
    const fmt = /png/i.test(im.blob.type) ? "PNG" : "JPEG";
    try {
      doc.addImage(dataUrl, fmt, (W - dw) / 2, 50, dw, dh);
    } catch (e) {
      doc.setTextColor(179, 38, 30); doc.setFontSize(11);
      doc.text("Could not embed this image; attach it separately.", M, 70);
    }
  }

  return doc;
}
